name:                FType
version:             0.1.0.0
github:              "hassanAlAwwadi/FType"
license:             BSD3
author:              "Stephan van der Small, Hassan Al Awwadi"
copyright:           "2019 Stephan van der Small, Hassan Al Awwadi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/FType#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- random

library:
  source-dirs: src

executables:
  FType-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FType

tests:
  FType-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FType
